# Site settings
title: Effie Liouta
description: Web Developer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Effie Liouta
user_description: Hi, my name's Effie and I'm a Web Developer. As well as web developer I also have experience as a graphic designer. I have worked at a number of companies gaining teamwork skill.
user_title: Web Developer
email: effieliouta@gmail.com
# twitter_username: lorem_ipsum
instagram_username: effie_lt
linkedin_username: effie-lt
github_username:  e-liouta
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
